development:
  adapter: postgresql
  encoding: unicode
  database: myth_development  #name is name of app _development
  pool: 5
  host: localhost
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: myth_production  #name is name of app _development
  pool: 5
  host: localhost
  username: postgres
  password:
