
development:
  adapter: postgresql
  encoding: unicode
  database: queueing_math_development
  pool: 5
  host: localhost
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: queueing_math_test
  pool: 5
  host: localhost
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: queueing_math_production
  pool: 5
  host: localhost
  username: postgres
  password:
